### ISSUE TITLE
Compatibility with ELK stack version 5

### ISSUE THREAD

**Issue by openmomo** [ITLinuxCL/zimbra_logstash#7]
Hi,

Is there any plan to update the files for version 5 compatibility?

All templates sem to work with new version but the ones using zimbra.log which are postfix related.

Thanks.

**Comment by pbruna** [comment]
Hello,
Did you configure rsyslog to use high precision timestamp?

**Comment by openmomo** [comment]
I have found myself few minutes ago that TIMESTAMP_ISO8601 wasnt matching when processing POSTFIX pattern. That should be the problem.

Thank you!

**Comment by pbruna** [comment]
@openmomo its working now?
If so, please share what you did to make it work and close de issue.
Also, Im looking for help with the docs.

**Comment by openmomo** [comment]
Sure,

problem was at the format of the log timestamp. Didnt match TIMESTAMP_ISO8601 as in

`POSTFIX %{TIMESTAMP_ISO8601:created_at} %{SYSLOGHOST:hostname} %{COMPID}:`

Just checked in http://grokconstructor.appspot.com/do/automatic for a compatible format and got CISCOTIMESTAMP as good. Example:  

`Feb  9 09:30:52`

Now I have to review other fields for possible unmacthing. Is there any easy wa to do that?

**Comment by pbruna** [comment]
@openmomo the real issue here is that I forgot to document that is necessary to modify the syslog software to use High Resolution Time.

This High Resolution Time allows the software to sort the log records by the real time they occurred. With out this you end with several record hapepenning at the same second, which is not real.

In conclusion the best way to make this work is to use this repo confit as it is and configure Your syslog software to use HRT

**Comment by openmomo** [comment]
Got it. That should be the way to go, but in this case I have no rights to change syslog config.

Ill give the owner of the servers the advice for having correct time values.

Thanks again.
